from __future__ import annotations

from jsonschema_ts._emitter import _strip_root_interface, assemble


def test_assemble_models_only():
    result = assemble(
        models="export interface User { name: string; }",
        procedures="",
        banner="",
    )
    assert "export interface User" in result
    assert "Models" in result
    assert "Procedures" not in result


def test_assemble_procedures_only():
    result = assemble(models="", procedures="export interface API { ... }", banner="")
    assert "export interface API" in result
    assert "Procedures" in result
    assert "Models" not in result


def test_assemble_both():
    models = "export interface User { name: string; }"
    procedures = "export interface API { foo(): Promise<void>; }"
    result = assemble(models=models, procedures=procedures, banner="")
    assert "Models" in result
    assert "Procedures" in result
    assert result.index("Models") < result.index("Procedures")


def test_assemble_with_banner():
    result = assemble(
        models="export interface X { x: number; }",
        procedures="",
        banner="/* my banner */",
    )
    assert "my banner" in result


def test_assemble_default_banner():
    result = assemble(models="export interface X { x: number; }", procedures="")
    assert "generated by pyrpc codegen" in result


def test_assemble_empty():
    result = assemble(models="", procedures="", banner="")
    assert result == ""


def test_strip_root_interface():
    ts_code = """export interface Post {
  title: string;
}

export interface __ROOT__ {
  _Post_ref: Post;
}

export interface Author {
  name: string;
}
"""
    result = _strip_root_interface(ts_code)
    assert "__ROOT__" not in result
    assert "export interface Post" in result
    assert "export interface Author" in result


def test_strip_root_interface_no_root():
    ts_code = "export interface Foo { x: number; }"
    result = _strip_root_interface(ts_code)
    assert result == "export interface Foo { x: number; }"


def test_strip_root_interface_first_in_output():
    ts_code = """export interface __ROOT__ {
  _Post_ref: Post;
}
export interface Post {
  title: string;
}
"""
    result = _strip_root_interface(ts_code)
    assert "__ROOT__" not in result
    assert "export interface Post" in result


def test_strip_root_interface_custom_name():
    ts_code = """export interface CustomRoot {
  x: number;
}

export interface Foo {
  y: number;
}
"""
    result = _strip_root_interface(ts_code, root_name="CustomRoot")
    assert "CustomRoot" not in result
    assert "Foo" in result
