from __future__ import annotations

import re
import shutil
import unicodedata

from jsonschema_ts._errors import NodeRequiredError

DEFAULT_BANNER = """/**
 * @generated by pyrpc codegen
 * @see https://github.com/pyrpc/jsonschema-ts
 *
 * DO NOT EDIT — changes will be overwritten.
 * To regenerate: pyrpc codegen <source>
 */
/* eslint-disable */
"""


def _ensure_npx() -> None:
    if shutil.which("npx") is None:
        raise NodeRequiredError(
            "jsonschema-ts requires Node.js >= 18 and npx. "
            "Install Node.js from https://nodejs.org/"
        )


def _to_safe_name(name: str) -> str:
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"[^a-zA-Z0-9]", " ", s)
    s = _to_pascal_case(s)
    if not s:
        s = "GeneratedType"
    return s


def _to_pascal_case(s: str) -> str:
    parts = s.split()
    result: list[str] = []
    for part in parts:
        sub_parts = re.findall(
            r"[A-Z]?[a-z]+|[A-Z]+(?=[A-Z][a-z]|\d|\b)|[A-Z]+|\d+",
            part,
        )
        if not sub_parts:
            sub_parts = [part]
        result.extend(sub_parts)
    return "".join(seg.capitalize() for seg in result if seg)


def _ensure_schema_has_title(schema: dict, name: str) -> None:
    if "title" not in schema:
        schema["title"] = name


def _postprocess(ts_code: str) -> str:
    return ts_code.strip()
