from __future__ import annotations

import re
import shutil
import unicodedata

from jsonschema_ts._errors import NodeRequiredError


DEFAULT_BANNER = """/**
 * @generated by pyrpc codegen
 * @see https://jsonschema-ts.vercel.app
 *
 * DO NOT EDIT — changes will be overwritten.
 * To regenerate: pyrpc codegen <source>
 */
/* eslint-disable */
"""


def _ensure_npx() -> None:
    if shutil.which("npx") is None:
        raise NodeRequiredError(
            "jsonschema-ts requires Node.js >= 18 and npx. "
            "Install Node.js from https://nodejs.org/"
        )


def _to_safe_name(name: str) -> str:
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("ascii")
    s = re.sub(r"[^a-zA-Z0-9_]", " ", s)
    s = s.title().replace(" ", "")
    if not s:
        s = "GeneratedType"
    return s


def _ensure_schema_has_title(schema: dict, name: str) -> None:
    if "title" not in schema:
        schema["title"] = name


def _postprocess(ts_code: str, name: str) -> str:
    return ts_code.strip()
